export const SKILLS_BY_CATEGORY: Record<string, string[]> = {
  painting: [
    "Interior Painting",
    "Exterior Painting",
    "Spray Painting",
    "Decorative Finishes",
    "Waterproofing",
    "Surface Preparation",
  ],
  plumbing: [
    "Pipe Installation",
    "Leak Repairs",
    "Drain Cleaning",
    "Geyser Installation",
    "Bathroom Fitting",
    "Water Pressure Issues",
  ],
  electrical: [
    "Wiring & Rewiring",
    "DB Board Installation",
    "Fault Finding",
    "Light Fitting",
    "Solar Installation",
    "Prepaid Meter Installation",
  ],
  "building-renovation": [
    "Bricklaying",
    "Concrete Work",
    "Extensions",
    "Demolition",
    "Foundation Work",
    "Drywall Installation",
  ],
  tiling: [
    "Floor Tiling",
    "Wall Tiling",
    "Grouting",
    "Waterproofing",
    "Tile Removal",
    "Mosaic Work",
  ],
  roofing: [
    "Roof Installation",
    "Leak Repairs",
    "Waterproofing",
    "IBR Roofing",
    "Thatching",
    "Guttering",
  ],
  welding: [
    "MIG Welding",
    "TIG Welding",
    "Arc Welding",
    "Gate Fabrication",
    "Security Bars",
    "Metal Fabrication",
  ],
  carpentry: [
    "Cabinet Making",
    "Door Installation",
    "Deck Building",
    "Furniture Repair",
    "Roof Trusses",
    "Built-in Cupboards",
  ],
  plastering: [
    "Interior Plastering",
    "Exterior Plastering",
    "Skimming",
    "Coving",
    "Crack Repairs",
    "Skim Coating",
  ],
  handyman: [
    "General Repairs",
    "Furniture Assembly",
    "Hanging & Mounting",
    "Door Repairs",
    "Window Repairs",
    "Minor Plumbing",
  ],
};
